version: '3.3'

services:
  # Uncomment mongodb service, and nawah_app depends_on, MONGO_DB_HOST lines
  # in order to get a MongoDB service launched with your docker-compose for
  # using Nawah with it:
  # mongodb:
  #   image: mongo:4.2
  #   volumes:
  #     - ./db:/data/db
  #   restart: always
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: admin
  #     MONGO_INITDB_ROOT_PASSWORD: admin
  nawah_app:
    # depends_on:
    #   - mongodb
    build: .
    ports:
      - "8081:8081"
    environment:
      # MONGO_DB_HOST: admin:admin@mongodb:27017
      ENV: prod
      DEBUG: 1
